### ISSUE TITLE
Can't release 2.4.0 ... 

### ISSUE THREAD

**Issue by e2** [guard/guard-minitest#121]
I don't have access to release guard-minitest 2.4.0 (one commit before master), since I'm not an owner of the gem.

@rymai, @genericsteele, @yannlugrin - could and of you give me access and/or release 2.4.0? 

Thanks!

**Comment by rymai** [comment]
@e2 I've added you as owner to https://rubygems.org/gems/guard-minitest

**Comment by e2** [comment]
Thank you ssooooooo much!

**Comment by genericsteele** [comment]
Thanks @rymai and @e2!
