### ISSUE TITLE
2.4.0 breaks when loading Guard::Plugin

### ISSUE THREAD

**Issue by nateberkopec** [guard/guard-minitest#122]
```
/Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/guard-minitest-2.4.0/lib/guard/minitest/utils.rb:4:in `<module:Guard>': uninitialized constant Guard::Plugin (NameError)
	from /Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/guard-minitest-2.4.0/lib/guard/minitest/utils.rb:3:in `<top (required)>'
	from /Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/guard-minitest-2.4.0/lib/minitest/guard_minitest_plugin.rb:1:in `<top (required)>'
	from /Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:91:in `block in load_plugins'
	from /Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:85:in `each'
	from /Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:85:in `load_plugins'
	from /Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:114:in `run'
	from /Users/nateberkopec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/minitest-5.5.1/lib/minitest.rb:56:in `block in autorun'
```

Gemfile.lock

```
guard (2.10.5)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      pry (>= 0.9.12)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-minitest (2.4.0)
      guard-compat (~> 1.2)
      minitest (>= 3.0)
```

**Comment by e2** [comment]
@nateberkopec - thanks for reporting this! I'll fix is shortly (I don't use minitest myself, so I never thought about testing the autoloading).

**Comment by e2** [comment]
Let me know if anything else doesn't work.

Thanks!

**Comment by jasonrclark** [comment]
Running into something that looks like a similar problem still with 2.4.2.

```
/Users/jclark/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-minitest-2.4.2/lib/guard/minitest/notifier.rb:2:in `<module:Guard>': uninitialized constant Guard::Plugin (NameError)
	from /Users/jclark/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-minitest-2.4.2/lib/guard/minitest/notifier.rb:1:in `<top (required)>'
	from /Users/jclark/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/guard-minitest-2.4.2/lib/guard/minitest/runners/old_runner.rb:2:in `<top (required)>'
```

Relevant parts of Gemfile.lock
```
    guard (2.11.1)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-minitest (2.4.2)
      guard-compat (~> 1.2)
      minitest (>= 3.0)
    minitest (4.7.5)
```

Any other settings I can provide to help pin this down? Would you rather I open a separate issue?

**Comment by e2** [comment]
@jasonrclark - if you can, create a repo reproducing the issue, then I'll quickly work it out.

I'm not sure why the following is used: runners/old_runner.rb - I thought that was for plain Ruby unit/test.

Either way, a repo would help a lot (even if it's project specific, the error needs a better description on what to do).

**Comment by jasonrclark** [comment]
Seeing this on https://github.com/newrelic/rpm. I've pushed up a branch `guard-gemspec-update` with the latest, so grab that and then:

```
bundle install
bundle exec guard
```

I see the error immediately on startup of guard, and then on each subsequent time a file changes and guard tries to run.

**Comment by jasonrclark** [comment]
Oh, other context (don't know if it's pertinent), I'm running on Ruby 2.1.5.

**Comment by e2** [comment]
I reproduced it, and I'm not sure what the fix should be yet (it's a path only used in old minitest < 5).

Meanwhile, you could try upgrading Minitest to version 5 and try again.

**Comment by e2** [comment]
@jasonrclark - if you can, also move all the dev deps from the gemspec to the Gemfile. If a project is using bundler, there's no point in having any `add_development_dependency` entries, except with `bundler. (it's a long story, but basically `add_development_dependency` should be called `add_gem_build_dependency` - and that's it's only practical use).

**Comment by jasonrclark** [comment]
Thanks @e2! A lot of our tests have to run against Rails < 4.x which unfortunately aren't compatible with Minitest 5 :(

Will see about getting those dev dependencies moved out as well. Thanks for the insight.

**Comment by e2** [comment]
@jasonrclark - I'll release a fix for minitest 4 soon: https://github.com/guard/guard-minitest/pull/125

**Comment by e2** [comment]
@jasonrclark - The bonus of moving stuff to the Gemfile is that it gets required, and this is the cause - would fix things (because minitest is run using bundler, but neither 'guard' nor 'guard-compat' are explicitly required when building the minitest runner command line - and they shouldn't be because in some causes plugins should run without guard). 

Overall, there's kind of a mess (backward compatibility related) in terms of how things work, so feel free to ask about any details you need.

**Comment by e2** [comment]
@jasonrclark - 2.4.3 released and it works for me. Let me know if you have any other issues.

**Comment by jasonrclark** [comment]
Works for me, thanks for the quick turnaround @e2!

**Comment by e2** [comment]
@jasonrclark - glad to help. Have a nice day!
