### ISSUE TITLE
for Guard::Compat:Module (NoMethodError)

### ISSUE THREAD

**Issue by rocknrollMarc** [guard/guard-minitest#129]
10:13:10 - INFO - bundler guard added to Guardfile, feel free to edit it
10:13:10 - INFO - There are 2 definitions in your Guardfile for 'bundler', you may want to clean up your Guardfile as this could cause issues.
/Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/guard-1.8.3/lib/guard/guardfile.rb:62:in `initialize_template': undefined method `init' for Guard::Compat:Module (NoMethodError)
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/guard-1.8.3/lib/guard/guardfile.rb:89:in `block in initialize_all_templates'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/guard-1.8.3/lib/guard/guardfile.rb:89:in `each'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/guard-1.8.3/lib/guard/guardfile.rb:89:in `initialize_all_templates'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/guard-1.8.3/lib/guard/cli.rb:166:in `init'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/gems/guard-1.8.3/bin/guard:6:in `<top (required)>'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/bin/guard:23:in `load'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/bin/guard:23:in `<main>'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/bin/ruby_executable_hooks:15:in `eval'
        from /Users/marc/.rvm/gems/ruby-1.9.3-p551@rails3.2.6_social/bin/ruby_executable_hooks:15:in `<main>'

**Comment by rocknrollMarc** [comment]
source 'https://rubygems.org'

gem 'rails', '3.2.6'

gem 'devise'
gem 'simple_form'

group :development, :test do
	gem 'sqlite3'
end

group :production do
	gem "pg"
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'shoulda-context'

  gem 'guard'
  gem 'guard-rails'
  gem 'guard-minitest'
  gem 'guard-bundler'
  gem 'ruby-growl'
  gem 'terminal-notifier-guard'

  gem 'pry-rails'
  gem 'pry-nav'
  gem 'pry-doc'
  gem 'pry-coolline'
  gem 'awesome_print'
  gem 'pry-theme'

end

**Comment by rocknrollMarc** [comment]
Sorry nayve I should say something to this hahahah. I am trying to use guard-minitest with rails sand it doest seem tp initialize it so this is what I get when I do guard init

**Comment by rocknrollMarc** [comment]
Ok it workes: here my solution


treebookready $> bundle update                                                                           [ ruby-1.9.3-p551@rails3.2.6_social ]
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.....
Using multi_json 1.11.0 (was 1.3.6)
Using rack 1.4.5 (was 1.4.1)
Using hike 1.2.3 (was 1.2.1)
Using tilt 1.4.1 (was 1.3.3)
Using mime-types 1.25.1 (was 1.19)
Using i18n 0.7.0 (was 0.6.0)
Using builder 3.0.4 (was 3.0.0)
Using polyglot 0.3.5 (was 0.3.3)
Using arel 3.0.3 (was 3.0.2)
Using journey 1.0.4
Using tzinfo 0.3.44 (was 0.3.33)
Using erubis 2.7.0
Using awesome_print 1.6.1
Using bundler 1.9.6
Using coderay 1.1.0
Installing execjs 2.5.2 (was 1.4.0)
Using thor 0.19.1 (was 0.15.4)
Using unicode_utils 1.4.0
Installing coffee-script-source 1.9.1.1 (was 1.3.3)
Installing hitimes 1.2.2
Using ffi 1.9.8
Using formatador 0.2.5
Using rb-fsevent 0.9.4
Using lumberjack 1.0.9
Installing rake 10.4.2 (was 0.9.2.2)
Installing bcrypt 3.1.10
Using method_source 0.8.2
Using slop 3.6.0
Using guard-compat 1.2.1
Using minitest 5.6.1
Using systemu 2.6.5
Installing orm_adapter 0.5.0 (was 0.4.0)
Using yard 0.8.7.6
Installing nenv 0.2.0
Installing shellany 0.0.1
Installing json 1.8.2 (was 1.7.3)
Using terminal-notifier-guard 1.6.4
Using rack-cache 1.2
Using rack-test 0.6.3 (was 0.6.1)
Using rack-ssl 1.3.4 (was 1.3.2)
Installing thread_safe 0.3.5
Using sprockets 2.1.4 (was 2.1.3)
Using activesupport 3.2.6
Using treetop 1.4.15 (was 1.4.10)
Using coolline 0.5.0
Installing shoulda-context 1.2.1 (was 1.0.0)
Installing coffee-script 2.4.1 (was 2.2.0)
Using rb-inotify 0.9.5
Using pry 0.10.1
Using guard-minitest 2.4.4
Using macaddr 1.7.1
Installing warden 1.2.3 (was 1.2.1)
Installing sass 3.4.13 (was 3.1.20)
Installing timers 4.0.1
Installing notiffany 0.0.6
Using activemodel 3.2.6
Installing rdoc 3.12.2 (was 3.12)
Using mail 2.4.4
Using pry-coolline 0.2.5
Using pry-doc 0.6.0
Using pry-nav 0.2.4
Using pry-rails 0.3.4
Using uuid 2.3.7
Installing uglifier 2.7.1 (was 1.2.6)
Using actionpack 3.2.6
Using activerecord 3.2.6
Using activeresource 3.2.6
Using ruby-growl 4.1
Using actionmailer 3.2.6
Using railties 3.2.6
Installing pry-theme 1.1.3 (was 1.0.1)
Using coffee-rails 3.2.2
Installing pg 0.18.1 (was 0.14.0)
Installing shoulda-matchers 2.8.0 (was 1.3.0)
Using rails 3.2.6
Installing celluloid 0.16.0
Installing responders 1.1.2
Installing simple_form 2.1.2 (was 2.0.2)
Installing sqlite3 1.3.10 (was 1.3.6)
Installing jquery-rails 3.1.2 (was 2.0.2)
Installing shoulda 3.5.0 (was 3.1.1)
Installing sass-rails 3.2.6 (was 3.2.5)
Installing listen 2.10.0 (was 1.3.1)
Installing devise 3.4.1 (was 2.1.2)
Installing guard 2.12.5 (was 1.8.3)
Installing guard-bundler 2.1.0 (was 1.0.0)
Installing guard-rails 0.7.1 (was 0.4.7)
Bundle updated!
treebookready $> rm Guardfile                                                                            [ ruby-1.9.3-p551@rails3.2.6_social ]
treebookready $> bundle exec guard init                                                                  [ ruby-1.9.3-p551@rails3.2.6_social ]
10:18:31 - INFO - Writing new Guardfile to /Users/marc/workspace/rails/social/treebookready/Guardfile
10:18:31 - INFO - bundler guard added to Guardfile, feel free to edit it
10:18:31 - INFO - minitest guard added to Guardfile, feel free to edit it
10:18:31 - INFO - rails guard added to Guardfile, feel free to edit it
treebookready $>

**Comment by e2** [comment]
@rocknrollMarc - it was an old version of Guard. When using Guard::Minitest, make sure you're using the latest versions of Guard and Guard::Minitest, because the way minitest initializes itself has caused many problems that only recently were fixed.
