### ISSUE TITLE
bundler error when `spring: true` is combined with bundler v1.12 in Rails 4.2 environment

### ISSUE THREAD

**Issue by rmm5t** [guard/guard-minitest#139]
**Steps to reproduce**:

1. `gem update --system`
2. `gem install bundler --version "~> 1.12.5"`
3. Configure a `Guardfile` with `guard :minitest, spring: true` on a Rails 4.2 environment

**Expected Behavior**:

* Test suite should run as expected, and use spring to run tests faster on each invocation

**Actual Behavior**:

**`require: cannot load such file -- bundler/setup`**

```
09:42:26 - INFO - Guard::Minitest 2.4.4 is running, with Minitest::Unit 5.9.0!
09:42:26 - INFO - Running: all tests
/Users/{user}/.rbenv/versions/2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/{user}/.rbenv/versions/2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/{user}/work/{myapp}/config/boot.rb:3:in `<top (required)>'
	from bin/rake:6:in `require_relative'
	from bin/rake:6:in `<main>'
```

**Known Workaround Option 1**: (downgrade bundler)

1. `gem uninstall -Ix bundler`
2. `gem install bundler --version "~> 1.11.2"`

**Known Workaround Option 2**: (turn off spring, resulting in slower tests)

* Remove `spring: true` from `Guardfile`

**Comment by rmm5t** [comment]
**Update**: I suspect this might be related to https://github.com/bundler/bundler/issues/4602

**Comment by e2** [comment]
I'm guessing it's because of this line:

https://github.com/guard/guard-minitest/blob/2db91fb/lib/guard/minitest/runner.rb#L135

Here's a fix: https://github.com/guard/guard-rspec/pull/378

See this issue: https://github.com/guard/guard-rspec/issues/369

**Comment by e2** [comment]
If you can prepare a PR based on the fix above, I can make a quick bugfix release.

I believe `with_clean_env` has been replaceable since forever, so I believe the config option can be skipped. (I haven't researched the differences much).

**Comment by rmm5t** [comment]
Thanks @e2. Good pointer.  I'll prepare a PR as soon as I can get to it.

**Comment by rmm5t** [comment]
@e2 PR submitted at #140. Skipped the extra config option. Thanks!

**Comment by e2** [comment]
FYI, I think bugs like this can now be reproduced with `gem_isolator`, like I used for `guard_rspec`: 

https://github.com/guard/guard-rspec/commit/f565af68f9d9fd29e24d0f34a297466d99db2ef4

I'll merge the PR without it, but from experience I know it's helpful to reproduce LOAD_PATH and bundler issues which Guard::Minitest is especially prone to.

Thanks again!

**Comment by e2** [comment]
Released. Let me know if there's anything else ;)

**Comment by rmm5t** [comment]
@e2 Thanks for super-fast turnaround.

**Comment by e2** [comment]
My pleasure :)
