### ISSUE TITLE
Running system tests on Rails 5.2

### ISSUE THREAD

**Issue by taq** [guard/guard-minitest#155]
Hi!

Not sure if it's something related to this gem or to Guard itself, but ... 
I have a Rails 5.2 app when there are some system tests. When running on Rails regular tests:

```
$ bundle exec rails test
Running: all tests
```

It runs ok, *without* my system tests. But when running with Guard and Minitest, I have:

```
$ bundle exec guard
20:16:33 - INFO - Guard::Minitest 2.4.6 is running, with Minitest::Unit 5.11.3!
20:16:33 - INFO - Running: all tests
Started with run options --guard --seed 39628
```

Notice the "Running: all tests". Then on some point the tests stops and I got an error like

```
Traceback (most recent call last):
/home/taq/.rvm/rubies/ruby-2.5.1/bin/ruby: no code specified for -e (RuntimeError)
```
Seems the system tests are running there, because when I remove the `test/system` dir it works ok.

Is there something I can configure on Guardfile to ignore the system test when running guard with Minitest?

Thanks!

**Comment by taq** [comment]
Ok, nevermind, I think I can live with that.

**Comment by fwolfst** [comment]
Same for Rails 6 and I'd like to find an answer to that.

**Comment by szTheory** [comment]
@fwolfst The monkey-patch here worked for me https://github.com/guard/guard-minitest/issues/116#issue-36560992
