### ISSUE TITLE
Any change triggers all tests

### ISSUE THREAD

**Issue by aximuseng** [guard/guard-minitest#158]
I stripped my Guardfile down to this.  If I edit a controller guard starts ALL tests.

```
guard :minitest, all_on_start: false, all_after_pass: false, spring: true do
  watch(%r{^app/controllers/(.+)_controller\.rb$})  { |m| "test/controllers/#{m[1]}_controller_test.rb" }
end
```

Am I missing something here?

**Comment by Adeynack** [comment]
I have a similar behavior.

```ruby
watch(%r{^test/(.*)\/?(.*)_test\.rb$})
```

Striped it down to this. Saving a specific test file triggers all of the tests, including the system tests.

**Comment by skelebrina** [comment]
I was having this issue as well.
I replaced `spring: true` with `spring: "bin/rails test"` and now it seems to run only the associated test for that file.

**Comment by Adeynack** [comment]
I confirm @skelebrina 's solution worked for us.

**Comment by aximuseng** [comment]
I can also confirm that the solution @skelebrina proposed seems to work on my end also. 👍
